name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: echo "@${secrets.OWNER}:registry=https://npm.pkg.github.com" > ~/.npmrc
      - run: echo "//npm.pkg.github.com/:_authToken=${secrets.NODE_AUTH_TOKEN}" > ~/.npmrc
      - run: yarn install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
